spring:
  application:
    name: cloud-user-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false
    username: user
    password: password

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliasese-package: com.ray.springcloud.entities

jwt:
  key: urX1aYaVyJUSVsmlRALiVh8XbFt9AOjFuerHYfpu8Mk=