server:
  port: 8001
  
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.gjt.mm.mysql.Driver
  url: jdbc:mysql://localhost:3306?useUnicode=true
  username: user
  password: password
    
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliasese-package: com.ray.springcloud.entities