server:
  port: 8001
  
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306?useUnicode=true&useSSL=false
    username: user
    password: password

eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8888/eureka/
      
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliasese-package: com.ray.springcloud.entities